config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end
  root to: 'home#index'

  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :groups, only: [:index, :new, :create] do
     resources :purchases, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_purchases, dependent: :destroy
  has_many :purchases, through: :group_purchases

  has_one_attached :icon
  validates :name, presence: true
  validates :icon, presence: true

  # after_destroy :total_purchases_group_delete

  # def total_purchases_group_delete
  #   group.decrement!(:total_purchases, purchase.amount)
  # end
end

app/models/group_purchase.rb
class GroupPurchase < ApplicationRecord
  belongs_to :group
  belongs_to :purchase

  after_create :total_purchases_group
  def total_purchases_group
    group.increment!(:total_purchases, purchase.amount)
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_purchases, dependent: :destroy
  has_many :groups, through: :group_purchases
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id'
  has_many :purchases, foreign_key: 'author_id'

  validates :name, :email, :password, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @current_user = current_user
    @groups = current_user.groups
  end

  def new
    @current_user = current_user
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to root_path, notice: 'Your category is created successfully 🎉'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @current_user = current_user
    @group = Group.find(params[:group_id])
    # @purchases = Purchase.all
    @group_purchases = Group.find(params[:group_id]).group_purchases.order(created_at: :desc)
  end

  def new
    @current_user = current_user
    @group = Group.find_by_id(params[:group_id])
    @available_groups = current_user.groups.reject { |f| @group.purchases.include?(f) }
  end

  def create
    @purchase = current_user.purchases.new(name: params[:name], amount: params[:amount])

    if @purchase.save
      @group_purchase = GroupPurchase.new(group_id: params[:groups], purchase_id: @purchase.id)
      @group_purchase.save
      redirect_to group_purchases_path(group_id: params[:groups]), notice: 'Your Transaction is created successfully 🎉'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<section class="d-flex flex-column">
 <div class="log-in d-flex justify-content-between align-items-center">
                 <%= image_tag "menu.png", class: "icon"  %>
                <li class="log"> <h2> CATEGORIES</h2></li>
              <%= image_tag "icon2.svg", class: "icon"  %>
                
</div>

<% @groups.each do |group| %>
  <%= link_to " /groups/#{group.id}/purchases" do %>
  <div class="groups d-flex justify-content-between">
  <% if group.icon.attached? %>
   <div class="img-div">
    <img class="img" src="<%= url_for(group.icon) %>">
    </div>
  <% end %>
 <p class="name-group"> <%= group.name %></p>
 <span class="name-group" > Total amount: <%= group.total_purchases %> $</span>
</div>
<% end %>
 <% end %>

 <%= link_to 'Add new Category', new_group_path, class:"add-category"  %>



</section>

app/views/groups/new.html.erb
<section>
 <div class="log-in d-flex justify-content-between align-items-center">
               <%= render partial: "shared/arrow"%>
                <li class="log"> <h2> ADD CATEGORY</h2></li>
              <%= image_tag "icon2.svg", class: "icon"  %>
</div>
<%= form_with model: @group do |f| %>

   <div class="field">
    <%= f.label :name, class:"mt-2" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name" %>
  </div>

   <div class="field">
    <%= f.label :icon , class:"mt-2" %>
    <%= f.file_field :icon, class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Add category", class: "add-category" %>
  </div>

<% end %>
</section>

app/views/home/index.html.erb
<section class="home d-flex flex-column justify-content-between align-items-center gap-2">
  <%= image_tag "third.png", height: 400  %>
  <div class="w-100 text-center">
  <%= link_to "Log in", '/users/sign_in', class: "btn btn-dark w-50 mb-2" %>  
  <%= link_to "Sign up", '/users/sign_up', class: "btn btn-dark border border-dark w-50 mb-2"%>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

   <%= render partial: "shared/navbar" %>
   <%= render partial: "shared/flash"%>
  <div class="container cont">
    <%= yield %>
  </div>
  </body>
</html>

app/views/purchases/index.html.erb
<section class="d-flex flex-column cont">
 <div class="log-in d-flex justify-content-between align-items-center">
              <%= render partial: "shared/arrow"%>
                <li class="log"> <h2> PURCHASES</h2></li>
              <%= image_tag "icon2.svg", class: "icon"  %>
                
</div>
 <div class="groups d-flex justify-content-between">
  <% if @group.icon.attached? %>
   <div class="img-div">
    <img class="img" src="<%= url_for(@group.icon) %>">
    </div>
  <% end %>
 <p class="name-group"> <%= @group.name %></p>
 <span class="name-group">Total amount:<%= @group.total_purchases %> $</span>
</div>


<% @group_purchases.each do |group_purchase| %>
<div class="groups d-flex flex-column justify-content-between">
  <p class="name-group"> <%= group_purchase.purchase.name %></p>
 <span class="name-group"> amount: <%= group_purchase.purchase.amount %>$ </span>
 </div>
<% end %>


<%= link_to 'Add new Purchase', "/groups/#{@group.id}/purchases/new", class:"add-category"  %>
</section>

app/views/purchases/new.html.erb
<section>
 <div class="log-in d-flex justify-content-between align-items-center">
               <%= render partial: "shared/arrow"%>
                <li class="log"> <h2> ADD PURCHASE</h2></li>
              <%= image_tag "icon2.svg", class: "icon"  %>
</div>
<%= form_with url: group_purchases_path, method: :post do |f| %>

   <div class="field">
    <%= f.label :name, class:"mt-2" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "name" %>
  </div>

    <div class="field">
    <%= f.label :amount, class:"mt-2" %><br />
    <%= f.text_field :amount, autofocus: true, class: "form-control", placeholder: "amount" %>
  </div>

<%# 
  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">
    food
  </label>
</div> %>

<div class="field">
    <%= f.label :groups, class:"mt-2" %><br />
    <%= f.select :groups, options_from_collection_for_select(@available_groups, 'id', 'name'), {}, { class: "form-control" }%>
  </div>

  <div class="actions">
    <%= f.submit "Add Purchase", class: "add-category" %>
  </div>

<% end %>
</section>

app/views/shared/_arrow.html.erb
                <span> 
               <%= link_to root_path do %>
               <%= image_tag "arrow.png", class: "icon"  %>
               <% end %>
               </span>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info" role="alert">
  <%= flash[:notice]%>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-warning" role="alert">
  <%= flash[:alert]%>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="d-flex align-items-center justify-content-between">
        <% if @current_user %>
         <div>
              <h1>Welcome to our budget App✨</h1>
          </div>
          <li class="nav-item">
            <%= link_to "Log out", '/users/sign_out' , data: { method: :delete }, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>